Lion Mite,4,5,635726,ID,NORMAL
ROUTER,5,6,635727,II,NORMAL
PR20,3,5,635728,II,NORMAL
ROTOZIP,5,4,635729,II,NORMAL
FA08,4,4,635710,II,NORMAL
DC-I,4,4,635711,II,NORMAL
HLA,4,4,635712,II,NORMAL
P10,5,8,635713,II,NORMAL
INHEMETER,2,2,635714,II,NORMAL
Ametek,5,3,635715,II,NORMAL


# Estructura = Modelo,Renglones,Columnas,NumeroParte,Origen,Recorrido
# SI = Superior izquierda
# SD = Superior derecha
# II = Inferior izquierda
# ID = Inferior derecha
# NORMAL = Cada renglón comienza desde el mismo lado
# SERPIENTE = Cada renglón cambia de dirección